#!/usr/bin/env python3
"""Generate the compact INDEX files that lean skills read instead of whole corpora.

Stdlib only. Deterministic: rows are sorted, output is UTF-8 with LF line
endings, and nothing time- or machine-dependent is written.

    python3 tools/build_index.py optimise-orm [--check]
    python3 tools/build_index.py doctrines    [--check]

Without --check the index is (re)written in place. With --check nothing is
written: both sides are normalised CRLF -> LF, and on drift a unified diff is
printed and the exit status is 1 (2 means the source itself is malformed).

Line ranges are 1-based, as `Read` displays them. `L<start>-<end>` in an index
means `Read(file, offset=<start>, limit=<end>-<start>+1)`. A check's range runs
from its `### CODE` heading line to the line before the next `###`/`##`
heading (headings inside code fences do not count) or to the last line.
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

OPTIMISE_ORM_CHECKS = "plugins/django-inquisition/skills/optimise-orm/checks"
DOCTRINES_DIR = "plugins/puritan/skills/doctrines"

GENERATED = "<!-- GENERATED by tools/build_index.py -- do not edit; edit the sources and regenerate. -->"

READ_MAPPING = (
    "Line ranges are 1-based, as `Read` displays them. `L<start>-<end>` means "
    "`Read(file, offset=<start>, limit=<end>-<start>+1)`: the range runs from the "
    "`### CODE` heading line to the line before the next heading."
)

SEVERITY_LEGEND = """\
## Severity legend

| Tier | Internal | When |
|---|---|---|
| Critical | `critical` always; `high` when `savings_midpoint >= 100ms` | Query-killers: N+1 loops, bulk-write loops, missing index on hot filter |
| Medium | `high` when `savings_midpoint < 100ms`, `medium` always, `low` when `savings_midpoint >= 50ms` | Meaningful improvements |
| Low | `low` when `savings_midpoint < 50ms` | Stylistic / micro-optimisations |
| Header banner | `info` | Context: audit framework detected, signal-context info |
"""


class SourceError(Exception):
    """The source files are malformed (exit status 2)."""


def read_lf(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")


def cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def headings(lines: list[str]) -> list[tuple[int, int, str]]:
    """(1-based line, level, text) for every `##`/`###` heading outside code fences."""
    out: list[tuple[int, int, str]] = []
    fence: tuple[str, int] | None = None  # (char, length) of the open fence
    for i, line in enumerate(lines, 1):
        m = re.match(r"\s{0,3}(`{3,}|~{3,})(.*)$", line)
        if m:
            char, length, rest = m.group(1)[0], len(m.group(1)), m.group(2)
            if fence is None:
                if char == "`" and "`" in rest:
                    pass  # inline code such as ```x``` text, not a fence opener
                else:
                    fence = (char, length)
            elif char == fence[0] and length >= fence[1] and not rest.strip():
                fence = None
            continue
        if fence is not None:
            continue
        h = re.match(r"(#{2,3})\s+(.*?)\s*$", line)
        if h:
            out.append((i, len(h.group(1)), h.group(2)))
    return out


def section_end(hs: list[tuple[int, int, str]], idx: int, total: int, max_level: int) -> int:
    """Last line of heading idx's section: line before the next heading of level <= max_level."""
    for line, level, _ in hs[idx + 1:]:
        if level <= max_level:
            return line - 1
    return total


# ---------------------------------------------------------------- optimise-orm

def parse_frontmatter(text: str, path: Path) -> tuple[str, list[dict[str, str]]]:
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise SourceError(f"{path}: no YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise SourceError(f"{path}: unterminated YAML frontmatter") from None
    name = ""
    checks: list[dict[str, str]] = []
    in_checks = False
    pending: tuple[str, int] | None = None
    for raw in lines[1:end]:
        if re.match(r"checks:\s*$", raw):
            in_checks = True
            continue
        if not in_checks:
            m = re.match(r"name:\s*(.*)$", raw)
            if m:
                name = m.group(1).strip().strip("'\"")
            continue
        m = re.match(r"\s*-\s+id:\s*(.*)$", raw)
        if m:
            checks.append({"id": m.group(1).strip().strip("'\"")})
            continue
        if pending is not None and raw.strip():
            if len(raw) - len(raw.lstrip()) > pending[1]:
                raise SourceError(f"{path}: {pending[0]}: multi-line values are not supported; use a one-line value")
            pending = None
        m = re.match(r"(\s+)(\w+):\s*(.*)$", raw)
        if m and checks:
            key, value = m.group(2), m.group(3).strip()
            if value[:1] in (">", "|"):
                raise SourceError(
                    f"{path}: {checks[-1]['id']}.{key}: folded/literal scalars ({value[:1]}) are not supported; use a one-line value")
            if value[:1] in ("'", '"'):
                quoted = re.match(r"(['\"])(.*?)\1(?:\s|$)", value)
                value = quoted.group(2) if quoted else value.strip("'\"")
            else:
                value = re.sub(r"\s+#.*$", "", value)  # trailing ` # comment` on unquoted values
            if not value:
                pending = (f"{checks[-1]['id']}.{key}", len(m.group(1)))
            checks[-1][key] = value
    return name, checks


def optimise_orm_index(root: Path) -> tuple[Path, str]:
    cdir = root / OPTIMISE_ORM_CHECKS
    if not cdir.is_dir():
        raise SourceError(f"{cdir}: not found")
    rows: list[tuple[str, str, dict[str, str], int, int]] = []
    problems: list[str] = []
    for gpath in sorted(p for p in cdir.glob("*.md") if p.name != "INDEX.md"):
        text = read_lf(gpath)
        lines = text.split("\n")
        if lines and lines[-1] == "":
            lines = lines[:-1]
        group, checks = parse_frontmatter(text, gpath)
        group = group or gpath.stem
        hs = headings(lines)
        spans: dict[str, tuple[int, int]] = {}
        for i, (line, level, title) in enumerate(hs):
            if level == 3 and re.fullmatch(r"[A-Z]+-\d+", title):
                if title in spans:
                    problems.append(f"{gpath.name}: duplicate section {title}")
                spans[title] = (line, section_end(hs, i, len(lines), 3))
        ids = [c["id"] for c in checks]
        for cid in ids:
            if cid not in spans:
                problems.append(f"{gpath.name}: frontmatter id {cid} has no `### {cid}` section")
        for cid in spans:
            if cid not in ids:
                problems.append(f"{gpath.name}: section {cid} is missing from the frontmatter")
        for c in checks:
            if c["id"] in spans:
                start, end = spans[c["id"]]
                rows.append((group, gpath.name, c, start, end))
    if problems:
        raise SourceError("\n".join(problems))
    rows.sort(key=lambda r: (r[1], r[2]["id"]))
    out = [
        "# Check Index",
        "",
        GENERATED,
        "",
        f"{len(rows)} checks across {len({r[1] for r in rows})} group files. "
        "Master lookup for `optimise-orm`: which file owns each code, its default severity, "
        "its one-line rule, the first-pass trigger, and where its section sits.",
        "",
        READ_MAPPING,
        "",
        "`kind` and `trigger` are empty until a check declares them in its group file's frontmatter.",
        "",
        "| ID | Group | Severity | Kind | Check | Trigger | Span |",
        "|---|---|---|---|---|---|---|",
    ]
    for group, fname, c, start, end in rows:
        out.append(
            "| {id} | {g} | {sev} | {kind} | {title} | {trig} | {f} L{s}-{e} |".format(
                id=c["id"], g=group, sev=cell(c.get("severity_base", "")), kind=cell(c.get("kind", "")),
                title=cell(c.get("title", "")), trig=cell(c.get("trigger", "")),
                f=f"{fname}", s=start, e=end,
            )
        )
    out += ["", SEVERITY_LEGEND.rstrip("\n"), ""]
    return cdir / "INDEX.md", "\n".join(out)


# ------------------------------------------------------------------- doctrines

SECTION_ORDER = [
    "When to Use", "Why Use It", "Pros and Cons", "Applicable Directories", "Violation Catalog",
    "Allowed Exceptions", "Cross-Reference", "Sources and Authority", "Detection Signatures",
]


def first_sentence(paragraph: str) -> str:
    flat = " ".join(paragraph.split())
    m = re.match(r"(.+?[.!?])(\s|$)", flat)
    return (m.group(1) if m else flat).strip()


def sentence_with(paragraph: str, pattern: str) -> str:
    flat = " ".join(paragraph.split())
    for s in re.split(r"(?<=[.!?])\s+", flat):
        if re.search(pattern, s, re.I):
            return s.strip()
    return ""


def brief(text: str, limit: int) -> str:
    """Drop a trailing ` -- explanation`, collapse whitespace, cut at `limit` characters."""
    flat = re.split(r"\s+[\u2014\u2013-]{1,2}\s+", " ".join(text.split()), maxsplit=1)[0]
    return flat if len(flat) <= limit else flat[: limit - 1].rstrip() + "\u2026"


def doctrine_entry(path: Path) -> dict:
    lines = read_lf(path).split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
    hs = headings(lines)
    top = {t: (i, line) for i, (line, level, t) in enumerate(hs) if level == 2}
    missing = [s for s in SECTION_ORDER if s not in top]
    if missing:
        raise SourceError(f"{path.name}: missing sections: {', '.join(missing)}")
    order = [top[s][1] for s in SECTION_ORDER]
    if order != sorted(order):
        raise SourceError(f"{path.name}: sections are out of template order")

    def body(name: str) -> list[str]:
        i, line = top[name]
        end = section_end(hs, i, len(lines), 2)
        return lines[line:end]  # lines after the heading line, 0-based slice

    title = next((l[2:].strip() for l in lines if l.startswith("# ")), path.stem)
    when_paras = "\n".join(body("When to Use")).strip().split("\n\n")
    when = when_paras[0] if when_paras else ""
    cat_i, cat_line = top["Violation Catalog"]
    cat_end = section_end(hs, cat_i, len(lines), 2)
    cat_lines = lines[cat_line:cat_end]
    ids = re.findall(r"^\|\s*([A-Z]{2,5})-(\d+)\s*\|", "\n".join(cat_lines), re.M)
    prefixes = sorted({p for p, _ in ids})
    nums = sorted(int(n) for _, n in ids)
    categories = [t for line, level, t in hs if level == 3 and cat_line < line <= cat_end]

    def signals(sub: str) -> list[str]:
        sig_i, sig_line = top["Detection Signatures"]
        sig_end = section_end(hs, sig_i, len(lines), 2)
        for j, (line, level, t) in enumerate(hs):
            if level == 3 and t == sub and sig_line < line <= sig_end:
                end = min(section_end(hs, j, len(lines), 3), sig_end)
                return [m.group(1).strip() for l in lines[line:end]
                        if (m := re.match(r"-\s+(.*)$", l))]
        return []

    xref = [m.group(1) for l in body("Cross-Reference")
            if (m := re.match(r"-\s+\*\*([\w.-]+\.md)\*\*", l))]
    audit_start = top["Applicable Directories"][1]
    audit_end = top["Cross-Reference"][1] - 1
    return {
        "name": path.stem, "file": path.name, "title": title,
        "prefix": "/".join(prefixes), "lo": nums[0] if nums else 0, "hi": nums[-1] if nums else 0,
        "rules": len(ids), "categories": categories,
        "when": first_sentence(when), "when_not": sentence_with(when, r"\b(not|overkill|avoid|skip)\b"),
        "dir": signals("Directory signals"), "file_sig": signals("File signals"),
        "anti": signals("Anti-signals"), "xref": xref,
        "audit": f"L{audit_start}-{audit_end}",
    }


def doctrines_index(root: Path) -> tuple[Path, str]:
    ddir = root / DOCTRINES_DIR
    if not ddir.is_dir():
        raise SourceError(f"{ddir}: not found")
    entries, problems = [], []
    for p in sorted(ddir.glob("*.md")):
        if p.name.startswith("_") or p.name in ("INDEX.md", "README.md"):
            continue
        try:
            entries.append(doctrine_entry(p))
        except SourceError as exc:
            problems.append(str(exc))
    names = {e["file"] for e in entries}
    seen: dict[str, str] = {}
    for e in entries:
        for pre in e["prefix"].split("/"):
            if pre in seen:
                problems.append(f"{e['file']}: ID prefix {pre} also used by {seen[pre]}")
            seen[pre] = e["file"]
    if problems:
        raise SourceError("\n".join(problems))
    out = [
        "# Doctrine Index", "", GENERATED, "",
        f"{len(entries)} doctrines. Read this instead of the doctrine files for discovery and planning.",
        "", READ_MAPPING.replace("`### CODE` heading line", "doctrine section line"),
        "", "Each `## <name>` is the file `<name>.md` in this folder. `audit:` is the contiguous span Applicable Directories through Allowed Exceptions, "
        "the only part an auditor needs.", "",
    ]
    for e in entries:
        planned = [x if x in names else f"{x} (planned)" for x in e["xref"]]
        out += [
            f"## {e['name']}", "",
            f"- ids: {e['prefix']}-{e['lo']:03d} .. {e['prefix']}-{e['hi']:03d} ({e['rules']} rules)",
            f"- when: {cell(brief(e['when'], 70))}",
            *([f"- when not: {cell(brief(e['when_not'], 50))}"] if e["when_not"] else []),
            f"- dir signals: {cell('; '.join(brief(s, 80) for s in e['dir'][:6])) or 'none'}",
            f"- file signals: {cell('; '.join(brief(s, 56) for s in e['file_sig'][:3])) or 'none'}",
            f"- anti-signals: {cell('; '.join(brief(s, 80) for s in e['anti'][:3])) or 'none'}",
            f"- cross-refs: {', '.join(planned) or 'none'}",
            f"- audit: {e['audit']}", "",
        ]
    return ddir / "INDEX.md", "\n".join(out)


# ------------------------------------------------------------------------ main

GENERATORS = {"optimise-orm": optimise_orm_index, "doctrines": doctrines_index}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("index", choices=sorted(GENERATORS))
    ap.add_argument("--check", action="store_true", help="exit 1 with a diff if the committed index drifts")
    ap.add_argument("--root", type=Path, default=REPO, help="repo root (default: this checkout)")
    args = ap.parse_args(argv)
    try:
        target, content = GENERATORS[args.index](args.root)
    except SourceError as exc:
        print(f"build_index: {args.index}: malformed source\n{exc}", file=sys.stderr)
        return 2
    if args.check:
        have = read_lf(target) if target.exists() else ""
        if have == content:
            return 0
        rel = target.relative_to(args.root) if target.is_relative_to(args.root) else target
        sys.stdout.writelines(difflib.unified_diff(
            have.splitlines(keepends=True), content.splitlines(keepends=True),
            fromfile=f"{rel} (committed)", tofile=f"{rel} (generated)"))
        print(f"\nbuild_index: {rel} has drifted; run `python3 tools/build_index.py {args.index}`",
              file=sys.stderr)
        return 1
    with open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
